import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import LeftSide from "../components/LeftSide";
import RightSide from "../components/RightSide";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex   mx-auto">
        {/* LeftSide */}
        <LeftSide />
        {/* Feed */}
        <Feed />
        {/* RightSide */}
        <RightSide />
      </div>
    </div>
  );
}
